development:
  facebook_key: "1460789050899765"
  facebook_secret: "f57e59a989a5a4bd91f70a134fe6eb3f"

  twitter_key: "128185562-aMzSJ8FgOJNV9PUKXsznCdnrVDh99u8e3f0YgD1M"
  twitter_secret: "mSJG5zW6cJbs1E8cfpFPU7HdThCFzFipzJguApuF61pHHBJnvQ"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

production:
  facebook_key: "YOUR_KEY"
  facebook_secret: "YOUR_SECRET"

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
